export interface TrademarkCertificate {
  certificateType: string;
  badgeType: string;
  borderStyle: string;
  countryEn: string;
  countryAr: string;
  ministryEn: string;
  ministryAr: string;
  departmentEn: string;
  departmentAr: string;
  documentTitleEn: string;
  documentTitleAr: string;
  legalActEn: string;
  legalActAr: string;
  trademarkNameEn: string;
  trademarkNameAr: string;
  trademarkType: string;
  applicationNumber: string;
  certificateNumber: string;
  classNumber: string;
  priorityData: string;
  proprietorNameEn: string;
  proprietorNameAr: string;
  proprietorAddressEn: string;
  proprietorAddressAr: string;
  goodsServicesEn: string;
  goodsServicesAr: string;
  registrarPositionEn: string;
  registrarPositionAr: string;
  registrarNameEn: string;
  registrarNameAr: string;
  sealColor: string;
  sealStyle: string;
  showStamp: boolean;
  showSignature: boolean;
  showWatermark: boolean;
  signatureStyle: string;
  presetLogoId: string;
  status: "REGISTERED" | "PENDING";
  statusAr: string;
  uploadedLogoUrl?: string;
  qrCodeUrl?: string;
  dateOfFiling: string;
  dateOfRegistration: string;
  expiryDate: string;
  gazetteNumber: string;
  isVerified?: boolean;
  oppositions?: {
    id: string;
    reporterName: string;
    reporterEmail: string;
    reason: string;
    conflictingBrandName: string;
    statusOfOpposition: "PENDING" | "UNDER_REVIEW" | "DISMISSED" | "EXAMINER_DECISION";
    dateFiled: string;
    description: string;
  }[];
}
